# Generated by Django 4.2.10 on 2026-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_match_evaluation_type_match_max_skill_level_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external_avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
